- src/components/GlobalForms/index.js
- src/components/Header/index.js
- src/components/NewForm/Choices.js
- src/components/NewForm/index.js
- src/components/ViewResponses/Analytics.js
- src/index.js
- src/utils/nostr.js
Fixes https://github.com/abhay-raizada/nostr-forms/issues/10
> Global Feed, Blank validations

- src/components/FillForm/NostrForm.js
- src/components/FillForm/SignAndSubmit.js
- src/components/NewForm/index.js
- src/utils/nostr.js
Fixes https://github.com/abhay-raizada/nostr-forms/issues/6
> Add Self Sign forms

- src/components/FillForm/NostrForm.js
- src/components/NewForm/index.js
- src/components/ViewResponses/Analytics.js
- src/components/ViewResponses/index.js
- src/utils/nostr.js
Removed Public Response feature, because of a possible exploit in the implementation
> General Fixes post nip07

- LICENSE
- src/components/GlobalForms/index.js
- src/components/NewForm/FormSettings.js
- src/components/NewForm/QuestionForm.js
- src/components/NewForm/index.js
- src/components/ViewResponses/Analytics.js
- src/constants/index.js
- src/utils/nostr.js
- Added remove from global feed feature
- Add License
> UI Changes: Cleaner Interface

- package.json
- src/components/ViewResponses/Analytics.js
- src/components/ViewResponses/Export.tsx
- src/components/ViewResponses/Responses.js
- src/components/ViewResponses/index.js
- yarn.lock
Added export to excel and css
Can consider adding https://docs.sheetjs.com/docs/demos/grid/xs/ for viewing the responses
> fix: added download excel and csv

- src/components/MyForms/index.js
- src/components/NewForm/FormSettings.js
- src/components/NewForm/QuestionsList.js
- src/components/NewForm/index.js
- src/constants/index.js
> Add "Save Drafts" feature for unpublished forms

- README.md
- packages/formstr-sdk/docs/v1/design.md
- packages/formstr-sdk/src/formstr/formstr.test.js
- packages/formstr-sdk/src/formstr/formstr.ts
- packages/formstr-sdk/src/interfaces/v1/index.ts
@rramaa  we also need a validator spec for responses
> Add Send Responses to SDK

- packages/formstr-app/src/index.css
- packages/formstr-app/src/index.js
- packages/formstr-sdk/package.json
removed some overrides.
the `colorItemTextSelected` is inherited from `colorPrimary` and `primaryColor` by default is white
> Config overrides

- packages/formstr-app/src/App.js
- packages/formstr-app/src/containers/FormFiller/SubmitButton/submit.tsx
- packages/formstr-app/src/containers/MyForms/components/Local/FormDetails.tsx
- packages/formstr-app/src/containers/MyForms/components/Local/index.tsx
- packages/formstr-app/src/containers/MyForms/components/Nostr/index.tsx
- packages/formstr-app/src/containers/MyForms/configs/menuConfig.tsx
- packages/formstr-app/src/containers/MyForms/style.ts
- packages/formstr-app/src/containers/Responses/Export.tsx
- packages/formstr-app/src/containers/Responses/Responses.style.ts
- packages/formstr-app/src/containers/Responses/Responses.tsx
- packages/formstr-app/src/containers/Responses/summary.style.ts
- packages/formstr-sdk/src/formstr/formstr.ts
Sync local forms to nostr profile.
> V1 Export To Excel & Sync Local Forms to Nostr Profile

- packages/formstr-sdk/src/formstr/formstr.ts
The formspec is fine, so it isn't discarded but the answer is sent as null @rramaa should we remove null from the formspec?  im not sure if it's even allowed
> Fix condition where answer is null

- README.md
Move from the old telegram link
> Change Support Chanel

- packages/formstr-app/src/containers/Dashboard/FormCards/LocalFormCard.tsx
- packages/formstr-app/src/containers/FormFillerNew/index.tsx
- packages/formstr-app/src/containers/ResponsesNew/index.tsx
- packages/formstr-app/src/nostr/common.ts
- packages/formstr-sdk/src/formstr/nip101/fetchFormResponses.tsx
- packages/formstr-sdk/src/formstr/nip101/fetchFormTemplate.tsx
- packages/formstr-sdk/src/formstr/nip101/sendResponses.ts
Fixed Responnse labels, timeout on submit, code cleanup
> Fixes from Beta Testing

- packages/formstr-app/src/containers/ResponsesNew/index.tsx
- Add link to njump.me for npub
- Only make the author Column sticky
- Add Submissions column for number of edits
- Only show last edit per user
> Improve Responses Page

- packages/formstr-app/src/index.css
can't access figma for color gradient but have fixed button alignments and dropdown style 
issue: #186
> fix button alignments and dropdown style

- packages/formstr-app/src/containers/PublicForms/index.tsx
- packages/formstr-app/src/nostr/publicForms.ts
- packages/formstr-app/src/utils/utility.ts
Remove tables, add a cards style UX
> New Public Forms Screen

- packages/formstr-app/src/components/Header/configs.tsx
- packages/formstr-app/src/containers/CreateFormNew/components/FormSettings/Sharing/Participants.tsx
- packages/formstr-app/src/containers/CreateFormNew/components/FormSettings/Sharing/index.tsx
- packages/formstr-app/src/containers/CreateFormNew/components/FormSettings/index.tsx
- packages/formstr-app/src/containers/CreateFormNew/providers/FormBuilder/index.tsx
- packages/formstr-app/src/containers/Dashboard/FormCards/LocalFormCard.tsx
- packages/formstr-app/src/containers/Dashboard/index.tsx
- packages/formstr-app/src/containers/FormFillerNew/index.tsx
- packages/formstr-app/src/containers/PublicForms/index.tsx
- packages/formstr-app/src/nostr/common.ts
- packages/formstr-app/src/nostr/createForm.tsx
- packages/formstr-app/src/nostr/publicForms.ts
- packages/formstr-app/src/old/containers/MyForms/components/Submissions/index.tsx
- packages/formstr-app/src/utils/formUtils.ts
- packages/formstr-app/src/utils/utility.ts
TODO: Move Encrypt form setting outside Visibility Menu and rename it as "Make form contents public?"
> Make Forms Private by Default

- packages/formstr-app/src/containers/Dashboard/FormCards/LocalForms.tsx
- packages/formstr-app/src/containers/Dashboard/index.tsx
Enrich the existing local forms dashboard
> Fetch Form data on-device screen

- packages/formstr-app/public/docs/faq.md
> fixed bug : incorrect text in faq section 

- packages/formstr-app/src/containers/CreateFormNew/components/AnswerSettings/index.tsx
> Removed required and Right Answer from labels

- packages/formstr-app/src/containers/PublicForms/index.tsx
resolves #258 
https://github.com/user-attachments/assets/b4404e46-7ba1-4fdd-a927-833c6de704fb
> added skeleton loader for global forms page

- packages/formstr-app/src/containers/FormFillerNew/SubmitButton/submit.tsx
> fix issue #245

- packages/formstr-app/src/templates/blank.ts
- packages/formstr-app/src/templates/index.ts
> Update blank.ts issue , Fixes #262

- packages/formstr-app/src/containers/PublicForms/index.tsx
The Global Forms page would crash if a form event from a relay didn't have all the expected tags (d, name, etc.). This just adds some checks so it doesn't break if that happens.
> Fix crash on Global Forms

- packages/formstr-app/src/containers/CreateFormNew/components/QuestionCard/index.tsx
- packages/formstr-app/src/containers/CreateFormNew/components/QuestionsList/index.tsx
https://github.com/user-attachments/assets/cdcd9197-0bc7-42e9-896b-3bd052382761
Please take a look at it , and let me know if more modifications are needed.
> feat: enhance drag-and-drop functionality in QuestionCard and QuestionList components

- packages/formstr-app/src/containers/ResponsesNew/Export.tsx
This PR improves error handling in the `Export` component by replacing the generic `catch` block with specific error type checking.
This follows up on a comment from the previous PR (merged) suggesting that it’s better to capture specific types of errors rather than using a generic `catch`.
- Handle `unknown` error type safely
- Add checks for known error messages (dynamic import failures, data conversion issues, file generation errors)
https://github.com/abh3po/nostr-forms/pull/232#discussion_r2027529532
> Improve export error handling

- README.md
> Fixed: Readme

- packages/formstr-app/src/containers/FormFillerNew/QuestionNode/InputTypes/TimeFiller.tsx
- packages/formstr-app/src/containers/ResponsesNew/Export.tsx
The TimePicker needs to be made controlled by managing its value using React state. By passing the value prop and using useState, we maintain full control over the component's internal state.
> Fix TimePicker Value Reset Issue

- packages/formstr-app/src/containers/ResponsesNew/index.tsx
- packages/formstr-app/src/nostr/fetchFormTemplate.tsx
> refactor: Remove console logs from response handling and form templae fetching

- packages/formstr-app/src/containers/Dashboard/FormCards/Purchases.tsx
> Fixed : Purchases.tsx

- packages/formstr-app/src/containers/CreateFormNew/components/FormDetails/index.tsx
The issue Resolved the overflowing of modal content when a user publish a form in mobile
> Fixed : Width for mobile
